[package]
name = "duocast-desktop"
version = "1.2.0"
description = "DuoCast Desktop"
authors = ["DuoCast"]
edition = "2021"

[lib]
name = "duocast_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
tauri = { version = "2.11.1", features = [] }
serde = { version = "1", features = ["derive"] }
windows-capture = "2.0.1"
wasapi = "0.23.0"
